// UART Message Constants 
// Automatically generated  by uart_msg_const_gen.py at 02:30PM on June 16, 2017

`ifndef UART_MSG_CONSTS_H
`define UART_MSG_CONSTS_H

// Generic constants
`define UART_MSG_WIDTH 64
`define UART_MSG_SIZE [63:0]
`define UART_MSG_BITS [63:0]
`define UART_HEADER_WIDTH 8
`define UART_HEADER_SIZE [7:0]
`define UART_HEADER_BITS [7:0]
`define UART_PAYLOAD_WIDTH 56
`define UART_PAYLOAD_SIZE [55:0]
`define UART_PAYLOAD_BITS [63:8]

// Received num
`define UART_HEADER_RECEIVED_NUM 8'd0
`define UART_RECEIVED_NUM_ADDR_WIDTH 9
`define UART_RECEIVED_NUM_ADDR_SIZE [8:0]
`define UART_RECEIVED_NUM_ADDR_BITS [16:8]
`define UART_RECEIVED_NUM_ADDR_PAYLOAD_BITS [8:0]
`define UART_RECEIVED_NUM_DATA_WIDTH 36
`define UART_RECEIVED_NUM_DATA_SIZE [35:0]
`define UART_RECEIVED_NUM_DATA_BITS [52:17]
`define UART_RECEIVED_NUM_DATA_PAYLOAD_BITS [44:9]
`define UART_RECEIVED_NUM_TOTAL_PAYLOAD_WIDTH 45
`define UART_RECEIVED_NUM_TOTAL_PAYLOAD_SIZE [44:0]
`define UART_RECEIVED_NUM_TOTAL_PAYLOAD_BITS [52:8]

// Replace num
`define UART_HEADER_REPLACE_NUM 8'd1
`define UART_REPLACE_NUM_ADDR_WIDTH 9
`define UART_REPLACE_NUM_ADDR_SIZE [8:0]
`define UART_REPLACE_NUM_ADDR_BITS [16:8]
`define UART_REPLACE_NUM_ADDR_PAYLOAD_BITS [8:0]
`define UART_REPLACE_NUM_DATA_WIDTH 36
`define UART_REPLACE_NUM_DATA_SIZE [35:0]
`define UART_REPLACE_NUM_DATA_BITS [52:17]
`define UART_REPLACE_NUM_DATA_PAYLOAD_BITS [44:9]
`define UART_REPLACE_NUM_TOTAL_PAYLOAD_WIDTH 45
`define UART_REPLACE_NUM_TOTAL_PAYLOAD_SIZE [44:0]
`define UART_REPLACE_NUM_TOTAL_PAYLOAD_BITS [52:8]

// Mod params
`define UART_HEADER_MOD_PARAMS 8'd2
`define UART_MOD_PARAMS_CYCLES_PER_HALF_PERIOD_WIDTH 6
`define UART_MOD_PARAMS_CYCLES_PER_HALF_PERIOD_SIZE [5:0]
`define UART_MOD_PARAMS_CYCLES_PER_HALF_PERIOD_BITS [13:8]
`define UART_MOD_PARAMS_CYCLES_PER_HALF_PERIOD_PAYLOAD_BITS [5:0]
`define UART_MOD_PARAMS_TOTAL_PAYLOAD_WIDTH 6
`define UART_MOD_PARAMS_TOTAL_PAYLOAD_SIZE [5:0]
`define UART_MOD_PARAMS_TOTAL_PAYLOAD_BITS [13:8]

// Sys status
`define UART_HEADER_SYS_STATUS 8'd3
`define UART_SYS_STATUS_RUN_WIDTH 1
`define UART_SYS_STATUS_RUN_SIZE [0:0]
`define UART_SYS_STATUS_RUN_BITS [8:8]
`define UART_SYS_STATUS_RUN_PAYLOAD_BITS [0:0]
`define UART_SYS_STATUS_TOTAL_PAYLOAD_WIDTH 1
`define UART_SYS_STATUS_TOTAL_PAYLOAD_SIZE [0:0]
`define UART_SYS_STATUS_TOTAL_PAYLOAD_BITS [8:8]

// Mem params
`define UART_HEADER_MEM_PARAMS 8'd4
`define UART_MEM_PARAMS_NO_NUMS_WIDTH 9
`define UART_MEM_PARAMS_NO_NUMS_SIZE [8:0]
`define UART_MEM_PARAMS_NO_NUMS_BITS [16:8]
`define UART_MEM_PARAMS_NO_NUMS_PAYLOAD_BITS [8:0]
`define UART_MEM_PARAMS_TEST_MODE_WIDTH 1
`define UART_MEM_PARAMS_TEST_MODE_SIZE [0:0]
`define UART_MEM_PARAMS_TEST_MODE_BITS [17:17]
`define UART_MEM_PARAMS_TEST_MODE_PAYLOAD_BITS [9:9]
`define UART_MEM_PARAMS_PULSE_WIDTH_WIDTH 10
`define UART_MEM_PARAMS_PULSE_WIDTH_SIZE [9:0]
`define UART_MEM_PARAMS_PULSE_WIDTH_BITS [27:18]
`define UART_MEM_PARAMS_PULSE_WIDTH_PAYLOAD_BITS [19:10]
`define UART_MEM_PARAMS_PULSE_GAP_WIDTH 10
`define UART_MEM_PARAMS_PULSE_GAP_SIZE [9:0]
`define UART_MEM_PARAMS_PULSE_GAP_BITS [37:28]
`define UART_MEM_PARAMS_PULSE_GAP_PAYLOAD_BITS [29:20]
`define UART_MEM_PARAMS_TOTAL_PAYLOAD_WIDTH 30
`define UART_MEM_PARAMS_TOTAL_PAYLOAD_SIZE [29:0]
`define UART_MEM_PARAMS_TOTAL_PAYLOAD_BITS [37:8]

// Err fifo full
`define UART_HEADER_ERR_FIFO_FULL 8'd5
`define UART_ERR_FIFO_FULL_PAYLOAD_WIDTH 56
`define UART_ERR_FIFO_FULL_PAYLOAD_SIZE [55:0]
`define UART_ERR_FIFO_FULL_PAYLOAD_BITS [63:8]
`define UART_ERR_FIFO_FULL_PAYLOAD_PAYLOAD_BITS [55:0]
`define UART_ERR_FIFO_FULL_TOTAL_PAYLOAD_WIDTH 56
`define UART_ERR_FIFO_FULL_TOTAL_PAYLOAD_SIZE [55:0]
`define UART_ERR_FIFO_FULL_TOTAL_PAYLOAD_BITS [63:8]

// Err mem overrun
`define UART_HEADER_ERR_MEM_OVERRUN 8'd6
`define UART_ERR_MEM_OVERRUN_PAYLOAD_WIDTH 56
`define UART_ERR_MEM_OVERRUN_PAYLOAD_SIZE [55:0]
`define UART_ERR_MEM_OVERRUN_PAYLOAD_BITS [63:8]
`define UART_ERR_MEM_OVERRUN_PAYLOAD_PAYLOAD_BITS [55:0]
`define UART_ERR_MEM_OVERRUN_TOTAL_PAYLOAD_WIDTH 56
`define UART_ERR_MEM_OVERRUN_TOTAL_PAYLOAD_SIZE [55:0]
`define UART_ERR_MEM_OVERRUN_TOTAL_PAYLOAD_BITS [63:8]

// Err update whilst run
`define UART_HEADER_ERR_UPDATE_WHILST_RUN 8'd7
`define UART_ERR_UPDATE_WHILST_RUN_PAYLOAD_WIDTH 56
`define UART_ERR_UPDATE_WHILST_RUN_PAYLOAD_SIZE [55:0]
`define UART_ERR_UPDATE_WHILST_RUN_PAYLOAD_BITS [63:8]
`define UART_ERR_UPDATE_WHILST_RUN_PAYLOAD_PAYLOAD_BITS [55:0]
`define UART_ERR_UPDATE_WHILST_RUN_TOTAL_PAYLOAD_WIDTH 56
`define UART_ERR_UPDATE_WHILST_RUN_TOTAL_PAYLOAD_SIZE [55:0]
`define UART_ERR_UPDATE_WHILST_RUN_TOTAL_PAYLOAD_BITS [63:8]

// Err invalid msg
`define UART_HEADER_ERR_INVALID_MSG 8'd8
`define UART_ERR_INVALID_MSG_PAYLOAD_WIDTH 56
`define UART_ERR_INVALID_MSG_PAYLOAD_SIZE [55:0]
`define UART_ERR_INVALID_MSG_PAYLOAD_BITS [63:8]
`define UART_ERR_INVALID_MSG_PAYLOAD_PAYLOAD_BITS [55:0]
`define UART_ERR_INVALID_MSG_TOTAL_PAYLOAD_WIDTH 56
`define UART_ERR_INVALID_MSG_TOTAL_PAYLOAD_SIZE [55:0]
`define UART_ERR_INVALID_MSG_TOTAL_PAYLOAD_BITS [63:8]

// Ack
`define UART_HEADER_ACK 8'd9
`define UART_ACK_PAYLOAD_WIDTH 56
`define UART_ACK_PAYLOAD_SIZE [55:0]
`define UART_ACK_PAYLOAD_BITS [63:8]
`define UART_ACK_PAYLOAD_PAYLOAD_BITS [55:0]
`define UART_ACK_TOTAL_PAYLOAD_WIDTH 56
`define UART_ACK_TOTAL_PAYLOAD_SIZE [55:0]
`define UART_ACK_TOTAL_PAYLOAD_BITS [63:8]


`endif
